# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/Linux/ProgMod/Projet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/Linux/ProgMod/Projet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Linux/ProgMod/Projet/CMakeFiles /mnt/d/Linux/ProgMod/Projet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/Linux/ProgMod/Projet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named ant_sim

# Build rule for target.
ant_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ant_sim
.PHONY : ant_sim

# fast build rule for target.
ant_sim/fast:
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/build
.PHONY : ant_sim/fast

src/controllers/manager.o: src/controllers/manager.cpp.o

.PHONY : src/controllers/manager.o

# target to build an object file
src/controllers/manager.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/controllers/manager.cpp.o
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/controllers/manager.cpp.o
.PHONY : src/controllers/manager.cpp.o

src/controllers/manager.i: src/controllers/manager.cpp.i

.PHONY : src/controllers/manager.i

# target to preprocess a source file
src/controllers/manager.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/controllers/manager.cpp.i
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/controllers/manager.cpp.i
.PHONY : src/controllers/manager.cpp.i

src/controllers/manager.s: src/controllers/manager.cpp.s

.PHONY : src/controllers/manager.s

# target to generate assembly for a file
src/controllers/manager.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/controllers/manager.cpp.s
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/controllers/manager.cpp.s
.PHONY : src/controllers/manager.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/models/coord.o: src/models/coord.cpp.o

.PHONY : src/models/coord.o

# target to build an object file
src/models/coord.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/coord.cpp.o
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/coord.cpp.o
.PHONY : src/models/coord.cpp.o

src/models/coord.i: src/models/coord.cpp.i

.PHONY : src/models/coord.i

# target to preprocess a source file
src/models/coord.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/coord.cpp.i
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/coord.cpp.i
.PHONY : src/models/coord.cpp.i

src/models/coord.s: src/models/coord.cpp.s

.PHONY : src/models/coord.s

# target to generate assembly for a file
src/models/coord.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/coord.cpp.s
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/coord.cpp.s
.PHONY : src/models/coord.cpp.s

src/models/fourmi.o: src/models/fourmi.cpp.o

.PHONY : src/models/fourmi.o

# target to build an object file
src/models/fourmi.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/fourmi.cpp.o
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/fourmi.cpp.o
.PHONY : src/models/fourmi.cpp.o

src/models/fourmi.i: src/models/fourmi.cpp.i

.PHONY : src/models/fourmi.i

# target to preprocess a source file
src/models/fourmi.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/fourmi.cpp.i
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/fourmi.cpp.i
.PHONY : src/models/fourmi.cpp.i

src/models/fourmi.s: src/models/fourmi.cpp.s

.PHONY : src/models/fourmi.s

# target to generate assembly for a file
src/models/fourmi.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/fourmi.cpp.s
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/fourmi.cpp.s
.PHONY : src/models/fourmi.cpp.s

src/models/place.o: src/models/place.cpp.o

.PHONY : src/models/place.o

# target to build an object file
src/models/place.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/place.cpp.o
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/place.cpp.o
.PHONY : src/models/place.cpp.o

src/models/place.i: src/models/place.cpp.i

.PHONY : src/models/place.i

# target to preprocess a source file
src/models/place.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/place.cpp.i
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/place.cpp.i
.PHONY : src/models/place.cpp.i

src/models/place.s: src/models/place.cpp.s

.PHONY : src/models/place.s

# target to generate assembly for a file
src/models/place.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/models/place.cpp.s
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/models/place.cpp.s
.PHONY : src/models/place.cpp.s

src/views/affichage.o: src/views/affichage.cpp.o

.PHONY : src/views/affichage.o

# target to build an object file
src/views/affichage.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/views/affichage.cpp.o
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/views/affichage.cpp.o
.PHONY : src/views/affichage.cpp.o

src/views/affichage.i: src/views/affichage.cpp.i

.PHONY : src/views/affichage.i

# target to preprocess a source file
src/views/affichage.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/views/affichage.cpp.i
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/views/affichage.cpp.i
.PHONY : src/views/affichage.cpp.i

src/views/affichage.s: src/views/affichage.cpp.s

.PHONY : src/views/affichage.s

# target to generate assembly for a file
src/views/affichage.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/src/views/affichage.cpp.s
	$(MAKE) -f CMakeFiles/ant_sim.dir/build.make CMakeFiles/ant_sim.dir/src/views/affichage.cpp.s
.PHONY : src/views/affichage.cpp.s

tests/controllers/manager.o: tests/controllers/manager.cpp.o

.PHONY : tests/controllers/manager.o

# target to build an object file
tests/controllers/manager.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/controllers/manager.cpp.o
.PHONY : tests/controllers/manager.cpp.o

tests/controllers/manager.i: tests/controllers/manager.cpp.i

.PHONY : tests/controllers/manager.i

# target to preprocess a source file
tests/controllers/manager.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/controllers/manager.cpp.i
.PHONY : tests/controllers/manager.cpp.i

tests/controllers/manager.s: tests/controllers/manager.cpp.s

.PHONY : tests/controllers/manager.s

# target to generate assembly for a file
tests/controllers/manager.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/controllers/manager.cpp.s
.PHONY : tests/controllers/manager.cpp.s

tests/models/coord.o: tests/models/coord.cpp.o

.PHONY : tests/models/coord.o

# target to build an object file
tests/models/coord.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/coord.cpp.o
.PHONY : tests/models/coord.cpp.o

tests/models/coord.i: tests/models/coord.cpp.i

.PHONY : tests/models/coord.i

# target to preprocess a source file
tests/models/coord.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/coord.cpp.i
.PHONY : tests/models/coord.cpp.i

tests/models/coord.s: tests/models/coord.cpp.s

.PHONY : tests/models/coord.s

# target to generate assembly for a file
tests/models/coord.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/coord.cpp.s
.PHONY : tests/models/coord.cpp.s

tests/models/fourmi.o: tests/models/fourmi.cpp.o

.PHONY : tests/models/fourmi.o

# target to build an object file
tests/models/fourmi.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/fourmi.cpp.o
.PHONY : tests/models/fourmi.cpp.o

tests/models/fourmi.i: tests/models/fourmi.cpp.i

.PHONY : tests/models/fourmi.i

# target to preprocess a source file
tests/models/fourmi.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/fourmi.cpp.i
.PHONY : tests/models/fourmi.cpp.i

tests/models/fourmi.s: tests/models/fourmi.cpp.s

.PHONY : tests/models/fourmi.s

# target to generate assembly for a file
tests/models/fourmi.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/fourmi.cpp.s
.PHONY : tests/models/fourmi.cpp.s

tests/models/place.o: tests/models/place.cpp.o

.PHONY : tests/models/place.o

# target to build an object file
tests/models/place.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/place.cpp.o
.PHONY : tests/models/place.cpp.o

tests/models/place.i: tests/models/place.cpp.i

.PHONY : tests/models/place.i

# target to preprocess a source file
tests/models/place.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/place.cpp.i
.PHONY : tests/models/place.cpp.i

tests/models/place.s: tests/models/place.cpp.s

.PHONY : tests/models/place.s

# target to generate assembly for a file
tests/models/place.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/models/place.cpp.s
.PHONY : tests/models/place.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... run_tests"
	@echo "... rebuild_cache"
	@echo "... ant_sim"
	@echo "... src/controllers/manager.o"
	@echo "... src/controllers/manager.i"
	@echo "... src/controllers/manager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/models/coord.o"
	@echo "... src/models/coord.i"
	@echo "... src/models/coord.s"
	@echo "... src/models/fourmi.o"
	@echo "... src/models/fourmi.i"
	@echo "... src/models/fourmi.s"
	@echo "... src/models/place.o"
	@echo "... src/models/place.i"
	@echo "... src/models/place.s"
	@echo "... src/views/affichage.o"
	@echo "... src/views/affichage.i"
	@echo "... src/views/affichage.s"
	@echo "... tests/controllers/manager.o"
	@echo "... tests/controllers/manager.i"
	@echo "... tests/controllers/manager.s"
	@echo "... tests/models/coord.o"
	@echo "... tests/models/coord.i"
	@echo "... tests/models/coord.s"
	@echo "... tests/models/fourmi.o"
	@echo "... tests/models/fourmi.i"
	@echo "... tests/models/fourmi.s"
	@echo "... tests/models/place.o"
	@echo "... tests/models/place.i"
	@echo "... tests/models/place.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

